### ISSUE TITLE
Exception: The dimension of the vector and the columns number of the matrix mismatch

### ISSUE THREAD

**Issue by PlutoHDDev** [gyrdym/ml_algo#184]
Hello, I have a chart with many data points in my Flutter app and I am trying to draw a trend line in it as you can see in this example: https://google.github.io/charts/flutter/example/combo_charts/scatter_plot_line
To do so, I have programmed the class seen below and implemented the LinearRegressor in it. I want to display the line by determining the y-values for two values on the x-axis of my chart using my predict function and then drawing a line through those points. However, it seems that there is a bug in my predict function which you can see below and I can't quite figure it out. 
I can say, that in the train function I have two columns, in the first column are the x values and in the second column are the corresponding y values of the points in the chart. I then use this data to train the LinearRegressor. The predict function takes an x-value, which is why the ySeries, the second column, is empty there. With one row and two columns, the second of which is empty, I then try to predict this empty space, which is the y-value. 
I assume that something is wrong here in my implementation of the prediction, but unfortunately I don't understand what. I hope the error description is sufficient.

This is the error I get:
```dart
E/flutter ( 8937): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Exception: The dimension of the vector and the columns number of the matrix mismatch
E/flutter ( 8937): #0      MatrixImpl._matrixVectorMul (package:ml_linalg/src/matrix/matrix_impl.dart:500:7)
E/flutter ( 8937): #1      MatrixImpl.* (package:ml_linalg/src/matrix/matrix_impl.dart:89:14)
E/flutter ( 8937): #2      LinearRegressorImpl.predict (package:ml_algo/src/regressor/linear_regressor/linear_regressor_impl.dart:152:11)
E/flutter ( 8937): #3      AnalyticsLinearRegression.predict (package:trimlog/services/ml/analytics_linear_regression.dart:87:35)
E/flutter ( 8937): <asynchronous suspension>
E/flutter ( 8937): #4      _AnalyticGraphState.build.<anonymous closure>.<anonymous closure>.<anonymous closure>._predict.<anonymous closure> (package:trimlog/screens/analytics/analytics_graphs.dart:143:49)
E/flutter ( 8937): <asynchronous suspension>
E/flutter ( 8937):
```

This is the class used for the linear regression:

```dart
class AnalyticsLinearRegression {
  List<Trim> trims;
  final String xCategory;
  final String xParameter;
  final String yCategory;
  final String yParameter;

  AnalyticsLinearRegression(this.trims, this.xCategory, this.xParameter, this.yCategory, this.yParameter);

  List<Series> _prepareData() {
    // Remove trims which do not contain the parameter shown in this analytic
    List<Trim> temp = new List.from(trims);
    trims.forEach((trim) {
      Map<String, dynamic> map = trim.toMap();
      if ((!(map[xCategory] as Map).containsKey(xParameter)) || (map[xCategory][xParameter] == null) || (!(map[yCategory] as Map).containsKey(yParameter)) || (map[yCategory][yParameter] == null))
        temp.remove(trim);
    });
    trims = temp;
    // Extract the parameters shown in the analytic from the trims
    List x = [];
    List y = [];
    trims.forEach((trim) {
      Map<String, dynamic> map = trim.toMap();
      x.add((map[xCategory][xParameter] is List ? map[xCategory][xParameter].first : map[xCategory][xParameter]) * 1.0);
      y.add((map[yCategory][yParameter] is List ? map[yCategory][yParameter].first : map[yCategory][yParameter]) * 1.0);
    });
    Series xSeries = Series(xParameter, x); // First column, given parameter
    Series ySeries = Series(yParameter, y); // Second column, predicted parameter
    return [xSeries, ySeries];
  }

  Future train() async {
    final Iterable<Series> data = _prepareData();
    final dataFrame = DataFrame.fromSeries(data);
    if (dataFrame.rows.length <= 2) return; // <= 2 datapoints results in errors
    final targetColumnName = yParameter; // The second column (y) contains the parameter that I later want to predict
    final splits = splitData(dataFrame, [0.7]);
    final validationData = splits[0];
    // final testData = splits[1];
    final validator = CrossValidator.kFold(validationData, numberOfFolds: validationData.rows.length - 1);
    final createClassifier = (DataFrame samples) => LinearRegressor(
          samples,
          targetColumnName,
          optimizerType: LinearOptimizerType.gradient,
          iterationsLimit: 90,
          learningRateType: LearningRateType.decreasingAdaptive,
          batchSize: samples.rows.length,
        );
    final scores = await validator.evaluate(createClassifier, MetricType.rmse);
    final accuracy = scores.mean();
    print('Accuracy on root mean squared error (RMSE) validation: ${accuracy.toStringAsFixed(2)}');
    // final testSplits = splitData(testData, [1.00]);
    // final classifier = createClassifier(testSplits[0]);
    // final finalScore = classifier.assess(testSplits[1], MetricType.rmse);
    // print(finalScore.toStringAsFixed(2));
    // await classifier.saveAsJson(xParameter + '_' + yParameter + '_classifier.json');
    final classifier = createClassifier(dataFrame);
    await classifier.saveAsJson(await _classifierPath);
  }

  Future retrain(List<Trim> newData) async {
    final classifier = await _linearRegressor;
    trims = newData;
    final Iterable<Series> data = _prepareData();
    final dataFrame = DataFrame.fromSeries(data);
    final retrainedClassifier = classifier.retrain(dataFrame);
    await retrainedClassifier.saveAsJson(await _classifierPath);
  }

  /// Predicts the y value (seceond column) of a given x value (double)
  /// Can be used / Is used to get to points and draw a line through these points as a trendline (like here: https://google.github.io/charts/flutter/example/combo_charts/scatter_plot_line)
  Future<double> predict(double x) async {
    final classifier = await _linearRegressor;
    Series xSeries = Series(xParameter, [x]); // First column value (x)
    Series ySeries = Series(yParameter, []); // Second column value (y) should get predicted and returned, therefore this is empty
    final data = DataFrame.fromSeries([xSeries, ySeries]);
    final prediction = classifier.predict(data); // Predict the corresponding y value to the given x value
    return prediction.rows.first.first; // Prediction should only contain one row and this row should contain the predicted y value
  }

  Future<String> get _classifierPath async => (await getTemporaryDirectory()).path + "/" + xParameter + '_' + yParameter + '_classifier.json'; // Path where the classifier is saved
  Future<File> get _file async => File(await _classifierPath); // File containing the classifier (JSON)
  Future<String> get _encodedModel async => (await _file).readAsString(); // Classifier as JSON
  Future<LinearRegressor> get _linearRegressor async => LinearRegressor.fromJson(await _encodedModel); // Linear regressor from file
}
```

**Comment by gyrdym** [comment]
@PlutoHDDev Hi, thank you very much for creating the issue!  I'm sorry I constantly miss notifications about new issues, I need to set it up more properly. I'll take a look at your problem.

**Comment by gyrdym** [comment]
Still can't reproduce
